im1 = imread('cameraman.tif');
im2 = imread('rice.png');
fft_im1 = fft2(im1);
fft_im2 = fft2(im2);
res = (ifft2(fft_im1.*fft_im2));
%plot(abs(res));
subplot(2,2,1);
imagesc(abs(res));
title('FFt without pad');
temp1 = im1(:);
temp2 = im2(:);
con_out = conv2(im1,im2,'same');
c = isequal(con_out,abs(res));
subplot(2,2,2);
imagesc(con_out);
title('centre convolution');
%disp(c);
%part 2-b
val = mean((con_out(:)-res(:)).^2);
disp('error mean square without pad');
disp(val);
%part 2-c
temp1 = padarray(im1,[255,255],'post');
%temp1 = padarray(temp1,[127,127],'post');
temp2 = padarray(im2,[255,255],'post');
%temp2 = padarray(temp2,[127,127],'post');
out = (ifft2(fft2(temp1).*fft2(temp2)));
subplot(2,2,3);
imagesc(abs(out));
title('pad fft');
conv_full = conv2(im1,im2);
subplot(2,2,4);
imagesc(conv_full);
title('convolution');
d = isequal(abs(out),conv_full);
%disp(d);
val = mean((conv_full(:)-out(:)).^2);
disp('error mean square with pad');
disp(val);