testim = imread('inp1.png');
gauss = imfilter(testim,fspecial('gaussian',75,1));
motion = imfilter(testim,fspecial('motion',50,45));
avg  = imfilter(testim,fspecial('average',25));
med = medfilt2(testim);
stem(real(fft2(testim)));
figure;
subplot(3,2,[1 2]);
imshow(testim);
title('original');
subplot(3,2,3);
imshow(gauss);
title('gauss');
subplot(3,2,4);
imshow(motion);
title('motion');
subplot(3,2,5);
imshow(avg);
title('average');
subplot(3,2,6);
imshow(med);
title('median');