Img = imread("Faces.jpg");
[width,height,cdata] = size(Img);
subplot(2,2,1);
imshow(Img, []);
title("Original Color Image");
F1 = imread("F1.jpg");
[width,height,cdata] = size(F1);
subplot(2,2,2);
imshow(F1, []);
width = height;
height = width;
title("Single Face");
match = 1;
Output = normxcorr2(F1(:,:,match),Img(:,:,match));
subplot(2,2,3);
imshow(Output, []);
title("Normalised Images");
[maxV,maxI] = max(abs(Output(:)));
[y,x] = ind2sub(size(Output),maxI(1));
out1 = [(x-size(F1,2)) , (y-size(F1,1)) ];
subplot(2,2,4);
imshow(Img);
face = [out1(1) out1(2) width, height];
rectangle('position',face,'edgecolor','r','linewidth',2);
title("Face Detection");