[y,fs] = audioread('sa_re_ga_ma.wav');
test1 = smoothdata(y,'gaussian');
test2 = smoothdata(y,'sgolay');
test3 = smoothdata(y,'includenan');
test4 = smoothdata(y,'loess');
test5 = smoothdata(y,'lowess');
test6 = smoothdata(y,'movmean');
test7 = smoothdata(y,'movmedian');
test8 = smoothdata(y,'rloess');
test9 = smoothdata(y,'rlowess');
%plotting the different plots
subplot(5,2,1);
plot(y);
title('original');
subplot(5,2,2);
plot(test1);
title('Gaussian');
subplot(5,2,3);
plot(test2);
title('Sgolay');
subplot(5,2,4);
plot(test3);
title('IncludeNan');
subplot(5,2,5);
plot(test4);
title('loess');
subplot(5,2,6);
plot(test5);
title('lowess');
subplot(5,2,7);
plot(test6);
title('movmean');
subplot(5,2,8);
plot(test7);
title('movmedian');
subplot(5,2,9);
plot(test8);
title('rloess');
subplot(5,2,10);
plot(test9);
title('rlowessp');